FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends snort iproute2 iputils-ping curl && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/snort/rules /var/log/snort && \
    echo 'include $RULE_PATH/local.rules' >> /etc/snort/snort.conf


# Copia il file local.rules dentro il container
COPY local.rules /etc/snort/rules/local.rules

# Imposta la variabile RULE_PATH (molti snort.conf la usano)
ENV RULE_PATH=/etc/snort/rules

CMD ["snort","--daq","pcap","-i","any","-A","fast","-l","/var/log/snort","-c","/etc/snort/snort.conf","-k","none"]
