FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        snort libdaq2 iproute2 iputils-ping curl && \
    rm -rf /var/lib/apt/lists/*

# directory log
RUN mkdir -p /var/log/snort

# OPTIONAL: regole personalizzate
COPY local.rules /etc/snort/rules/local.rules
RUN sed -i 's|^var RULE_PATH .*|var RULE_PATH /etc/snort/rules|' /etc/snort/snort.conf

# *** RIMOZIONE della riga che forza il DAQ (se presente) ***
RUN sed -i '/^config daq/d' /etc/snort/snort.conf
