version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./server/db/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app-network

  server:
    build: ./server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    networks:
      - app-network

  client:
    build: ./client
    depends_on:
      - server
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
