version: '3.8'

services:
  db:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./server/db/db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    networks:
      - app-network

  client:
    build: ./client
    container_name: client
    depends_on:
    - server
    - squid
    environment:
    - http_proxy=http://squid:3128
    - https_proxy=http://squid:3128
    networks:
    - app-network
  snort:
    build: ./snort
    container_name: snort
    cap_add:
    - NET_ADMIN
    network_mode: "host"
    tty: true    
  squid:
    build: ./squid
    container_name: squid
    networks:
      - app-network
    ports:
      - "3128:3128" # proxy in uscita
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf:ro
      - ./squid/logs:/var/log/squid
volumes:
  db-data:

networks:
  app-network:
    driver: bridge
